### PR TITLE
add try catch for old mfxInit call #132

### PR DESCRIPTION
**Pull request by xelement**
## Issue

We are an app with tens of millions of users，recently we found some crash report show that mfxInit throw unhandled exception which do not be catched on user device，just see dump file below.

image

## Solution

just add try catch for mfxInit call

## How Tested

try catch do not need test

dump:
[3a0b8cfd-431a-4e62-8f13-6e3cc42156be.dmp](https://github.com/intel/libvpl/files/15150240/3a0b8cfd-431a-4e62-8f13-6e3cc42156be.dmp)

### CODE REVIEW

**Review by mav-intel — CHANGES_REQUESTED** [review]
Thanks for your PR.  A couple of requests:

1) Please sign-off on the PR as indicated in CONTRIBUTING.md
2) Please fix the code formatting to align with style guidance
3) Please fix the commit message to align with style guidance.  I recommend:
 `Catch unhandled exceptions when calling old init`
 
 You can check formatting yourself  by running `script/test lint`

**Comment by xelement** [comment]
> Thanks for your PR. A couple of requests:
> 
> 1. Please sign-off on the PR as indicated in [CONTRIBUTING.md](https://github.com/intel/libvpl/blob/master/CONTRIBUTING.md)
> 2. Please fix the code formatting to align with style guidance
> 3. Please fix the commit message to align with style guidance.  I recommend:
>    `Catch unhandled exceptions when calling old init`
> 
> You can check formatting yourself by running `script/test lint`

**Comment by xelement** [comment]
I'm sorry I didn't read the  CONTRIBUTING.md，I've already modified it

**Comment by mav-intel** [comment]
> ## How Tested
> try catch do not need test

@xelement Can you confirm that you no longer see the exception thrown in your environment after this change?

**Comment by xelement** [comment]
> > ## How Tested
> > try catch do not need test
> 
> @xelement Can you confirm that you no longer see the exception thrown in your local environment after this change?

It was not my local environment，it was feedback from our users.  maybe we can hold this pr for sometime. Our latest app version already includes this change, but it will take some time to see if it has any effect

**Comment by mav-intel** [comment]
Ok holding PR for now

**Review by mav-intel — CHANGES_REQUESTED** [review]
Waiting for results from local testing before moving forward

**Comment by jonrecker** [comment]
> It was not my local environment，it was feedback from our users. maybe we can hold this pr for sometime. Our latest app version already includes this change, but it will take some time to see if it has any effect

Thank you for the update. The attached dump file and the call stack in #132 do not include a reference to libvpl.dll, so it was not clear how this code is being called. Also the source code line numbers in the call stack seem to line up with the [MediaSDK implementation](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/api/mfx_dispatch/windows/src/main.cpp) of MFXInit() and MFXInitEx(), so perhaps that test was run using MediaSDK dispatcher (there is significant code in common). Any additional info about how this PR was validated would be helpful.

**Comment by tletnes** [comment]
Closing due to lack of activity, and appropriate changes are believed to have been made lower in the stack.

**Pull request closed without merging**
